2/add extract resource function
transparencia-mg/dtamg-py pull request #5
Opened 2022-01-20 20:32 UTC by gabrielbdornas

@fjuniorr para revisão, em conjunto com [este PR](https://github.com/transparencia-mg/age7/pull/241).

2022-01-20 20:34 UTC, gabrielbdornas commented
TODO para finalização da demanda:
- [ ] Revisão e fechamento [PR](https://github.com/transparencia-mg/dtamg-py/pull/5);
- [ ] Exclusão branch `2/add-extract-resource-function` local;
- [ ] Atualização dtamg-py para 0.1.3.
- [ ] Inclusão de conclusão da tarefa no relatório de atividades mensais.

2022-01-24 14:09 UTC, fjuniorr requested changes
Mandei um pequeno comentário para avaliação

2022-01-24 14:09 UTC, fjuniorr commented on dtamg_py/utils.py
> +  resources = []
`resources` vai sempre ter um item?

2022-01-24 14:15 UTC, gabrielbdornas commented on dtamg_py/utils.py
> +  resources = []
Vai sempre ser um

2022-01-28 15:30 UTC, fjuniorr approved these changes
As alterações no `dtamg-py` estão ok. 

Algumas alterações precisam ser feitas no https://github.com/transparencia-mg/age7/pull/241#pullrequestreview-866299039

2022-01-31 15:16 UTC, merged